name: flustars
description: Flutter common utils library. SpUtil, ScreenUtil, WidgetUtil. SharedPreferences Util. Screen info & Screen adaptation. get image size.
version: 0.2.5+1
author: thl <863764940@qq.com>
homepage: https://github.com/Sky24n/flustars

environment:
  sdk: ">=1.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # https://github.com/tekartik/synchronized.dart
  synchronized: '>=0.1.0 <3.0.0'
  # https://github.com/flutter/plugins/tree/master/packages/shared_preferences
  shared_preferences: '>=0.1.1 <2.0.0'